### PR TITLE
Unittests

### PR DESCRIPTION
**Pull request by cjdcordeiro**
as for the `agent`, also missing the tests for the main entrypoint, `run.py` (can be done later)

### CODE REVIEW

**Review by schaubl — COMMENTED** [review]
👍

**Comment by schaubl** [comment]
I finished reviewing the code but I had the following exception on my RPi4:
```python
Traceback (most recent call last):
  File "/opt/nuvlabox/./run.py", line 103, in <module>
    self_sup.write_container_stats_table_html()
  File "/opt/nuvlabox/system_manager/Supervise.py", line 189, in write_container_stats_table_html
    container_stats = json.load(cstats)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by schaubl** [comment]
Also the minimum requirements doesn't match the documentation.

**Comment by cjdcordeiro** [comment]
I've seen that warning as well. It's not critical. Can you open a separate bug for it?

I've aligned the min ram requirements, feel free to merge this

**Review by schaubl — APPROVED** [review]

**Pull request merged**
